version: '3.9'

services:
  db:
    restart: always
    image: postgres:14.7-alpine
    container_name: anyera_db
    env_file:
      - .env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d anyera"]
      interval: 5s
      timeout: 5s
      retries: 5
  service:
    build: .
    container_name: anyera_backend
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn -b 0.0.0.0:8000 AnyeraProject.wsgi:application"
    expose:
      - '8000'
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/mediafiles/
      - .env.docker:/app/.env
  nginx:
    image: nginx:latest
    container_name: nginx_anyera
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_value:/var/html/staticfiles
      - media_value:/var/html/mediafiles
    depends_on:
      - service
    ports:
      - '80:80'

volumes:
  postgres_data:
  static_value:
  media_value: