# Generated by Django 4.2.3 on 2023-07-03 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка питомца')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Возраст питомца')),
                ('kind_of_animal', models.CharField(max_length=255, verbose_name='Вид питомца')),
                ('photo', models.ImageField(blank=True, upload_to='animals_photo/', verbose_name='Фото питомца')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
    ]
